defaults:
  - _self_
  - /cluster: local
  - /algorithm: ppo
  - environment: cc_cartpole
  - search_space: ppo_cpu_hybrid
  - /experiments: cc_cartpole_ppo
  - override hydra/sweeper: HyperRS

hydra:
  sweeper:
    n_trials: 5
    search_space: ${search_space}
    sweeper_kwargs:
      maximize: true
      max_budget: ${environment.n_total_timesteps} 
      max_parallelization: 1 
      job_array_size_limit: 100
      seeds: [0]
  run:
    dir: results/rs/${algorithm}_${autorl.env_name}_${search_space.name}/${search_space.seed}/${seed}
  sweep:
    dir: results/rs/${algorithm}_${autorl.env_name}_${search_space.name}/${search_space.seed}/${seed}
  job:
    chdir: true

load_checkpoint: ""
jax_enable_x64: false
search_space.seed: 0
seed: 42

autorl:
  seed: ${seed}
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  deterministic_eval: ${environment.deterministic_eval}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean", "runtime"]
  optimize_objectives: "upper"
  n_steps: 10
  n_eval_steps: 10
  n_eval_episodes: 128