# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    gres: "gpu:1"
    timeout_min: 2880
    partition: c18g
    cpus_per_task: 16
    mem_per_cpu: 1000M
    account: p0021208
    setup:
      - source /rwthfs/rz/cluster/home/aq055502/projects/arlbench-smac-hyper/arlbench/.venv/bin/activate
      - module load CUDA/12.4.0
