# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 20
    partition: c23ms
    cpus_per_task: 8
    mem_per_cpu: 2000M
    setup:
      - source /rwthfs/rz/cluster/home/aq055502/projects/arlbench-smac-hyper/arlbench/.venv/bin/activate
