# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: dgx2
    gres: "gpu:1"
    timeout_min: 2880
    cpus_per_task: 2
    mem_per_cpu: 4000M
    setup:
      - export JAX_PLATFORM_NAME=gpu
      - source /rwthfs/rz/cluster/home/aq055502/projects/arlbench-smac-hyper/arlbench/.venv/bin/activate
      - module load CUDA/12.3.0
