# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 30
    partition: c23ms
    cpus_per_task: 8
    mem_per_cpu: 2000M
    setup:
      - module load GCCcore/12.2.0
      - module load Python/3.10.8
      - source .venv/bin/activate
