# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    gres: "gpu:1"
    timeout_min: 60
    partition: c23g
    cpus_per_task: 16
    setup:
      - module purge
      - module load GCCcore/12.2.0
      - module load Python/3.10.8
      - module load CUDA/11.8.0
      - module load cuDNN/8.6.0.163-CUDA-11.8.0
      - source .venv/bin/activate
