# @package _global_
defaults:
  - override /environment: brax_ant    
  - override /algorithm: ppo       

environment:
  n_envs: 256
  n_total_timesteps: 1000

hp_config:
  clip_eps: 0.2
  ent_coef: 0.01
  gae_lambda: 0.97
  learning_rate: 0.0003
  max_grad_norm: 0.5
  minibatch_size: 1024
  n_steps: 5
  vf_coef: 0.5
  update_epochs: 4
  normalize_observations: True

nas_config:
  activation: relu
  hidden_size: 256
  num_mlp_layers: 2